### ISSUE TITLE
Just a question.

### ISSUE THREAD

**Issue by edcomrocha** [hainakus/nexa-stratum-pool#1]
Looking at the name of the project it is understood that it is a pool for NEXA (nexa.org).

Am I correct or just a coincidence of the name?
Sorry for the question here, but I couldn't find another place to ask.

**Comment by juniorcines** [comment]
> Mirando el nombre del proyecto se entiende que es un pool para NEXA (nexa.org).
> 
> ¿Estoy en lo correcto o solo una coincidencia del nombre? Lo siento por la pregunta aquí, pero no pude encontrar otro lugar para preguntar.

I was reviewing the code and I can't find anywhere where the list of accepted algorithm appears in the files, I think this is not for nexa.
